GET http://localhost:8080 HTTP/1.1

###

POST http://localhost:8080/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "test1",
    "password": "test",
    "firstName": "test",
    "lastName": "test",
    "profileLink": "image",
    "dob": "1998-08-03",
    "age": 22,
    "roles": ["user"]
}

###

GET http://localhost:8080/api/test/user HTTP/1.1

###

POST http://localhost:8080/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8080/api/test/admin HTTP/1.1
x-access-token: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjIwNjQ2MzE3LCJleHAiOjE2MjA3MzI3MTd9.Q-6NKeBhonCRUu9Tqo4tVRlyKKMSs8m2m5_gpS_4adY
